### ISSUE TITLE
HTTP Server 'Gateway Timeout': https://download.jboss.org/jbosstools/updates/....

### ISSUE THREAD

**Issue by yamfun** [jbosstools/jbosstools-download.jboss.org#672]
When trying to get JBoss tool from Marketplace, got error:
HTTP Server 'Gateway Timeout': https://download.jboss.org/jbosstools/updates/....
HttpComponents connection error response code 504.

**Comment by jeffmaury** [comment]
Seems to be back now

**Comment by yamfun** [comment]
I tried more. 
On browser, I can browse: https://tools.jboss.org/downloads/jbosstools/2021-09/4.21.2.Final.html 
but, if I browse https://download.jboss.org/jbosstools/photon/stable/updates/
it will show
"An error occurred while processing your request.
Reference #97.67711977.1643107298.1383db8"

**Comment by jeffmaury** [comment]
It is working on my side:

![image](https://user-images.githubusercontent.com/695993/150964111-29a8d58f-8139-4966-bc25-145e72009fba.png)

Are you going through a proxy ?
